swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: No response was specified

  version: production
host: ragnarok-portal.brazilsouth.cloudapp.azure.com
#basePath: /
schemes:
  - https
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
components:
  securitySchemes:
    bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme.'
      name: Authorization
      in: header
security:
  #- basicAuth: []
  bearer: []
paths:
  /users:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      operationId: findUsers
      summary: Finds all users
  '/api/users/{id}/properties':
    get:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      operationId: findUsersById
      summary: Finds users by id
definitions:
  '':
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  User:
    properties:
      email:
        type: string
      id:
        format: int64
        type: integer
      name:
        type: string
#securityDefinitions:
#  basicAuth:
#    type: basic
#  apiKeyAuth:
#    type: apiKey
#    in: header
#    name: X-API-Key
tags:
  - description: Operations on users
    name: users
