swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: No response was specified

  version: production
host: ragnarok-portal.brazilsouth.cloudapp.azure.com
#basePath: /
schemes:
  - https
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
components:
  securitySchemes:
    Bearer:
      type: apiKey
      description: 'JWT Authorization header using the Bearer scheme.'
      name: Authorization
      in: header
security:
  #- basicAuth: []
  Bearer: []
paths:
  /users:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      operationId: findUsers
      summary: Finds all users
  '/api/users/{id}/properties':
    get:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      operationId: findUsersById
      summary: Finds users by id
  '/users/name/{name}':
    get:
      parameters:
        - description: Name to filter by
          in: path
          name: name
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      description: 'You can PUT, POST, and DELETE using this resource URL.'
      operationId: findUsersByName
      summary: Finds users by name
definitions:
  '':
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  User:
    properties:
      email:
        type: string
      id:
        format: int64
        type: integer
      name:
        type: string
#securityDefinitions:
#  basicAuth:
#    type: basic
tags:
  - description: Operations on users
    name: users
