swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: No response was specified

  version: production
host: ragnarok-portal.brazilsouth.cloudapp.azure.com
#basePath: /
schemes:
  - https
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - basicAuth: []
paths:
  /users:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      operationId: findUsers
      summary: Finds all users
  '/api/users/{id}/properties':
    delete:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      operationId: deleteUserById
      summary: Deletes a user by id
    get:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      operationId: findUsersById
      summary: Finds users by id
    post:
      parameters:
        - description: Id value to filter by
          in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      description: 'POST cannot be used to add computers, mobile devices, peripherals, vpp assignments to a user.'
      operationId: createUserById
      summary: Creates a new user by id
    put:
      parameters:
        - description: Id value to filter by
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      description: 'PUT cannot be used to add computers, mobile devices, peripherals, vpp assignments to a user.'
      operationId: updateUserById
      summary: Updates an existing user by id
  '/users/name/{name}':
    get:
      parameters:
        - description: Name to filter by
          in: path
          name: name
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - users
      description: 'You can PUT, POST, and DELETE using this resource URL.'
      operationId: findUsersByName
      summary: Finds users by name
definitions:
  '':
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  User:
    properties:
      email:
        type: string
      id:
        format: int64
        type: integer
      name:
        type: string
securityDefinitions:
  basicAuth:
    type: basic
tags:
  - description: Operations on users
    name: users
